name: melbetonline.com.br

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: npm ci
      - run: npm run production
      - run: rm -rf node_modules .git .github src configuration
      - run: rm .gitignore package.json package-lock.json webpack.config.js postcss.config.js
      # Deploy
      - run: cd ./ && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@161.35.7.198:/home/melbetonline_com_br/web/melbetonline.com.br/public_html/wp-content/themes/melbetonline-theme/
